In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [ ]:
b=np.array([[[1,2,3],[4,5,6],[4,5,6]],[[1,2,3],[4,5,6],[4,5,6]]])
b.shape

(2, 3, 3)

In [ ]:
a*b

ValueError: ignored

In [ ]:
a_reshape=a.reshape(2,3,1)
a_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [ ]:
a_reshape*b

array([[[ 1,  2,  3],
        [ 8, 10, 12],
        [12, 15, 18]],

       [[ 4,  8, 12],
        [20, 25, 30],
        [24, 30, 36]]])

In [ ]:
a_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [ ]:
a_reshape.T

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [ ]:
import numpy as np
mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))
mat1

array([[2, 0, 7],
       [7, 3, 6],
       [5, 3, 8],
       [6, 6, 1],
       [3, 6, 1]])

In [ ]:
mat2

array([[2, 4, 8],
       [0, 2, 0],
       [9, 0, 7],
       [8, 4, 6],
       [3, 0, 7]])

In [ ]:
mat1*mat2

array([[ 4,  0, 56],
       [ 0,  6,  0],
       [45,  0, 56],
       [48, 24,  6],
       [ 9,  0,  7]])

In [ ]:
np.dot(mat1,mat2)
# so in here we need to approach the difference between the element wise and the dot product element is 
#the simple multiplication but the dot product is which the matrix multiplication

ValueError: ignored

In [ ]:
mat2_reshape=mat2.reshape(3,5)
np.dot(mat1,mat2_reshape)

array([[32, 50, 37,  0, 53],
       [38, 91, 74, 21, 80],
       [42, 95, 64, 21, 90],
       [16, 84, 51, 42, 67],
       [10, 72, 27, 42, 61]])

In [ ]:
mat2_reshape

array([[2, 4, 8, 0, 2],
       [0, 9, 0, 7, 8],
       [4, 6, 3, 0, 7]])

In [ ]:
mat1

array([[2, 0, 7],
       [7, 3, 6],
       [5, 3, 8],
       [6, 6, 1],
       [3, 6, 1]])

In [ ]:
#incase we can use the tranxspose also in here
mat1.T
mat1.shape


(5, 3)

In [ ]:
mat1

array([[2, 0, 7],
       [7, 3, 6],
       [5, 3, 8],
       [6, 6, 1],
       [3, 6, 1]])

In [ ]:
np.dot(mat1.T,mat2)

array([[106,  46, 108],
       [ 93,  30,  99],
       [ 97,  44, 125]])

In [ ]:
import pandas as pd
a=np.random.randint(10,size=(5,3))
a

array([[4, 0, 9],
       [5, 9, 7],
       [3, 1, 2],
       [4, 1, 7],
       [0, 6, 6]])

In [ ]:
sales=pd.DataFrame(a,columns=["icecream","cashew_nuts","straberry"],index=["mon","tue","wed","thurs","fri"])
sales

icecream  cashew_nuts  straberry
mon           4            0          9
tue           5            9          7
wed           3            1          2
thurs         4            1          7
fri           0            6          6

In [ ]:
#prices
price=np.array([10,20,30])
b=pd.DataFrame(price.reshape(1,3),index=["price"],columns=["icecream","cashew_nuts","straberry"])
b

icecream  cashew_nuts  straberry
price        10           20         30

In [ ]:
total=np.dot(a,b.T)
sales["total"]=total
sales

icecream  cashew_nuts  straberry  total
mon           4            0          9    310
tue           5            9          7    440
wed           3            1          2    110
thurs         4            1          7    270
fri           0            6          6    300

In [ ]:
#/total=np.dot(a,b.T)
#sales["total"]=total
#sales["total"]
#sales


In [ ]:
# comaprsion operators
a1=np.array([1,2,3,4])
a2=np.array([4,3,2,1])
a1>a2

array([False, False,  True,  True])

In [ ]:
a1==a2

array([False, False, False, False])

In [ ]:
# sorting the arrays
random_array=np.random.randint(20,size=(3,5))
random_array

array([[ 9,  1,  2, 13, 17],
       [ 7, 17, 13, 19,  1],
       [11,  6,  6, 15,  9]])

In [ ]:
np.sort(random_array)

array([[ 1,  2,  9, 13, 17],
       [ 1,  7, 13, 17, 19],
       [ 6,  6,  9, 11, 15]])

In [ ]:
# suppose when we need to get the highest number poistion based on indexes
# lets see we can understand
np.argsort(random_array)

array([[1, 2, 0, 3, 4],
       [4, 0, 2, 1, 3],
       [1, 2, 4, 0, 3]])

In [ ]:
random_array

array([[ 9,  1,  2, 13, 17],
       [ 7, 17, 13, 19,  1],
       [11,  6,  6, 15,  9]])

In [ ]:
# in above the number 17 is highest number in first row so it given the index as 0 and then it continues
# suppose we need to find out the maximum and the minimum number
np.argmax(random_array,axis=1)

array([4, 3, 3])

In [ ]:
np.argmax(random_array,axis=0)

array([2, 1, 1, 1, 0])

In [ ]:
# when the axis is 0 it seen by columns and when the axis is 1 it seen the maximum value by the rows

In [ ]:
from matplotlib.image import imread
a=imread("/content/WIN_20220113_07_41_35_Pro.jpg")
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a

array([[[220, 159, 167],
        [221, 160, 168],
        [222, 161, 169],
        ...,
        [234, 166, 177],
        [233, 167, 177],
        [234, 168, 178]],

       [[222, 161, 169],
        [223, 162, 170],
        [224, 163, 171],
        ...,
        [234, 166, 177],
        [235, 167, 178],
        [235, 167, 178]],

       [[224, 163, 171],
        [224, 163, 171],
        [224, 163, 171],
        ...,
        [234, 166, 177],
        [235, 167, 178],
        [235, 167, 178]],

       ...,

       [[202, 144, 143],
        [202, 144, 143],
        [203, 143, 143],
        ...,
        [213, 153, 163],
        [213, 153, 163],
        [213, 153, 163]],

       [[200, 144, 143],
        [200, 144, 143],
        [202, 144, 143],
        ...,
        [213, 153, 163],
        [213, 153, 163],
        [213, 153, 163]],

       [[200, 144, 143],
        [200, 144, 143],
        [202, 144, 143],
        ...,
        [213, 153, 163],
        [213, 153, 163],
        [212, 152, 162]]

In [ ]:
a.shape,a.ndim

((720, 1280, 3), 3)

In [ ]:

# now our image is converted into the numbers